name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.event_name == 'push'&& !contains(join(github.event.head_commit.message,','),'#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokemon0902" #Must be unique in Heroku
          heroku_email: "zone.the.in@gmail.com"
          healthcheck: "https://pokemon0902.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
